import type { jobsTable } from "../schemas/jobs";

/**
 * Comprehensive seed data covering all 10 capabilities and edge cases
 * Total: 70 job roles
 */
export const comprehensiveJobSeeds: (typeof jobsTable.$inferInsert)[] = [
  // ENGINEERING (7 roles)
  {
    jobRoleName: "Junior Software Engineer",
    description: "Start your software development career with mentorship.",
    responsibilities: "Write code, code reviews, testing, collaboration",
    jobSpecLink: "https://company.com/careers/junior-software-engineer",
    location: "London, UK",
    capability: "Engineering",
    band: "Junior",
    closingDate: "2025-12-31",
    status: "open",
    numberOfOpenPositions: 5,
  },
  {
    jobRoleName: "Software Engineer",
    description: "Build and maintain critical software systems.",
    responsibilities: "Feature development, testing, code reviews, documentation",
    jobSpecLink: "https://company.com/careers/software-engineer",
    location: "Manchester, UK",
    capability: "Engineering",
    band: "Mid",
    closingDate: "2025-11-15",
    status: "open",
    numberOfOpenPositions: 3,
  },
  {
    jobRoleName: "Senior Software Engineer",
    description: "Lead technical initiatives and architecture decisions.",
    responsibilities: "System design, technical leadership, mentoring, standards",
    jobSpecLink: "https://company.com/careers/senior-software-engineer",
    location: "Birmingham, UK",
    capability: "Engineering",
    band: "Senior",
    closingDate: "2025-10-15",
    status: "open",
    numberOfOpenPositions: 2,
  },
  {
    jobRoleName: "Principal Engineer",
    description: "Define technical strategy across engineering.",
    responsibilities: "Strategic planning, architecture, executive discussions",
    jobSpecLink: "https://company.com/careers/principal-engineer",
    location: "London, UK",
    capability: "Engineering",
    band: "Principal",
    closingDate: "2025-12-15",
    status: "open",
    numberOfOpenPositions: 1,
  },
  {
    jobRoleName: "Frontend Engineer (React & TypeScript)",
    description: "Create beautiful UIs using React & TypeScript.",
    responsibilities: "React development, TypeScript, accessibility, performance",
    jobSpecLink: "https://company.com/careers/frontend-engineer",
    location: "Bristol, UK",
    capability: "Engineering",
    band: "Mid",
    closingDate: "2025-11-20",
    status: "open",
    numberOfOpenPositions: 3,
  },
  {
    jobRoleName: "Backend Engineer",
    description: "Build scalable backend services and APIs.",
    responsibilities: "API development, database design, microservices, monitoring",
    jobSpecLink: "https://company.com/careers/backend-engineer",
    location: "Remote, UK",
    capability: "Engineering",
    band: "Senior",
    closingDate: "2025-11-30",
    status: "open",
    numberOfOpenPositions: 4,
  },
  {
    jobRoleName: "Full Stack Engineer",
    description: "Work across the entire technology stack.",
    responsibilities: "Full stack development, API design, deployment",
    jobSpecLink: "https://company.com/careers/full-stack-engineer",
    location: "Leeds, UK",
    capability: "Engineering",
    band: "Mid",
    closingDate: "2025-10-01",
    status: "closed",
    numberOfOpenPositions: 0,
  },

  // DATA & ANALYTICS (7 roles)
  {
    jobRoleName: "Junior Data Analyst",
    description: "Learn to extract insights from complex datasets.",
    responsibilities: "Data analysis, SQL queries, reports, visualization",
    jobSpecLink: "https://company.com/careers/junior-data-analyst",
    location: "London, UK",
    capability: "Data & Analytics",
    band: "Junior",
    closingDate: "2025-12-10",
    status: "open",
    numberOfOpenPositions: 4,
  },
  {
    jobRoleName: "Data Analyst",
    description: "Analyze business data to drive strategic decisions.",
    responsibilities: "Advanced analytics, dashboards, reporting, modeling",
    jobSpecLink: "https://company.com/careers/data-analyst",
    location: "Manchester, UK",
    capability: "Data & Analytics",
    band: "Mid",
    closingDate: "2025-11-25",
    status: "open",
    numberOfOpenPositions: 2,
  },
  {
    jobRoleName: "Senior Data Scientist",
    description: "Lead data science initiatives and build ML models.",
    responsibilities: "Machine learning, statistical analysis, mentoring",
    jobSpecLink: "https://company.com/careers/senior-data-scientist",
    location: "Cambridge, UK",
    capability: "Data & Analytics",
    band: "Senior",
    closingDate: "2025-12-20",
    status: "open",
    numberOfOpenPositions: 1,
  },
  {
    jobRoleName: "Principal Data Architect",
    description: "Define data strategy and architecture.",
    responsibilities: "Data strategy, governance, technology evaluation",
    jobSpecLink: "https://company.com/careers/principal-data-architect",
    location: "London, UK",
    capability: "Data & Analytics",
    band: "Principal",
    closingDate: "2026-01-31",
    status: "open",
    numberOfOpenPositions: 1,
  },
  {
    jobRoleName: "Data Engineer",
    description: "Build and maintain data pipelines.",
    responsibilities: "ETL development, pipeline maintenance, automation",
    jobSpecLink: "https://company.com/careers/data-engineer",
    location: "Birmingham, UK",
    capability: "Data & Analytics",
    band: "Mid",
    closingDate: "2025-09-30",
    status: "closed",
    numberOfOpenPositions: 0,
  },
  {
    jobRoleName: "Senior Data Engineer",
    description: "Design scalable data infrastructure.",
    responsibilities: "Data architecture, performance tuning, team leadership",
    jobSpecLink: "https://company.com/careers/senior-data-engineer",
    location: "Remote, UK",
    capability: "Data & Analytics",
    band: "Senior",
    closingDate: "2025-12-05",
    status: "open",
    numberOfOpenPositions: 6,
  },
  {
    jobRoleName: "Machine Learning Engineer",
    description: "Build and deploy ML models at scale.",
    responsibilities: "ML development, model deployment, MLOps, optimization",
    jobSpecLink: "https://company.com/careers/machine-learning-engineer",
    location: "Oxford, UK",
    capability: "Data & Analytics",
    band: "Senior",
    closingDate: "2025-12-15",
    status: "open",
    numberOfOpenPositions: 2,
  },

  // WORKDAY (7 roles)
  {
    jobRoleName: "Junior Workday Consultant",
    description: "Learn Workday configuration and client support.",
    responsibilities: "Workday configuration, testing, documentation, training",
    jobSpecLink: "https://company.com/careers/junior-workday-consultant",
    location: "London, UK",
    capability: "Workday",
    band: "Junior",
    closingDate: "2025-12-01",
    status: "open",
    numberOfOpenPositions: 3,
  },
  {
    jobRoleName: "Workday HCM Consultant",
    description: "Configure Workday HCM solutions for enterprise clients.",
    responsibilities: "HCM configuration, business process design, testing",
    jobSpecLink: "https://company.com/careers/workday-hcm-consultant",
    location: "Reading, UK",
    capability: "Workday",
    band: "Mid",
    closingDate: "2025-11-18",
    status: "open",
    numberOfOpenPositions: 2,
  },
  {
    jobRoleName: "Senior Workday Integration Consultant",
    description: "Design complex Workday integrations.",
    responsibilities: "Integration design, Studio development, API development",
    jobSpecLink: "https://company.com/careers/senior-workday-integration",
    location: "Manchester, UK",
    capability: "Workday",
    band: "Senior",
    closingDate: "2025-11-28",
    status: "open",
    numberOfOpenPositions: 2,
  },
  {
    jobRoleName: "Principal Workday Architect",
    description: "Lead Workday architecture for enterprise implementations.",
    responsibilities: "Solution architecture, technical strategy, team leadership",
    jobSpecLink: "https://company.com/careers/principal-workday-architect",
    location: "London, UK",
    capability: "Workday",
    band: "Principal",
    closingDate: "2026-02-01",
    status: "open",
    numberOfOpenPositions: 1,
  },
  {
    jobRoleName: "Workday Financials Consultant",
    description: "Implement Workday Financial Management.",
    responsibilities: "Financial configuration, reporting, testing, training",
    jobSpecLink: "https://company.com/careers/workday-financials-consultant",
    location: "Leeds, UK",
    capability: "Workday",
    band: "Senior",
    closingDate: "2025-12-10",
    status: "open",
    numberOfOpenPositions: 1,
  },
  {
    jobRoleName: "Workday Payroll Consultant",
    description: "Configure Workday Payroll for UK clients.",
    responsibilities: "Payroll configuration, UK compliance, testing, support",
    jobSpecLink: "https://company.com/careers/workday-payroll-consultant",
    location: "Remote, UK",
    capability: "Workday",
    band: "Senior",
    closingDate: "2025-11-22",
    status: "open",
    numberOfOpenPositions: 2,
  },
  {
    jobRoleName: "Workday Project Manager",
    description: "Lead Workday implementation projects.",
    responsibilities: "Project management, client relations, risk management",
    jobSpecLink: "https://company.com/careers/workday-project-manager",
    location: "London, UK",
    capability: "Workday",
    band: "Senior",
    closingDate: "2025-10-05",
    status: "closed",
    numberOfOpenPositions: 0,
  },

  // PRODUCT (5 roles)
  {
    jobRoleName: "Junior Product Manager",
    description: "Start your product management career.",
    responsibilities: "Product research, documentation, user testing, metrics",
    jobSpecLink: "https://company.com/careers/junior-product-manager",
    location: "London, UK",
    capability: "Product",
    band: "Junior",
    closingDate: "2025-11-30",
    status: "open",
    numberOfOpenPositions: 2,
  },
  {
    jobRoleName: "Product Manager",
    description: "Drive product strategy and deliver user experiences.",
    responsibilities: "Roadmap planning, stakeholder management, user research",
    jobSpecLink: "https://company.com/careers/product-manager",
    location: "Manchester, UK",
    capability: "Product",
    band: "Mid",
    closingDate: "2025-12-05",
    status: "open",
    numberOfOpenPositions: 3,
  },
  {
    jobRoleName: "Senior Product Manager",
    description: "Lead product initiatives and define strategy.",
    responsibilities: "Product strategy, team leadership, executive presentations",
    jobSpecLink: "https://company.com/careers/senior-product-manager",
    location: "Bristol, UK",
    capability: "Product",
    band: "Senior",
    closingDate: "2025-11-18",
    status: "open",
    numberOfOpenPositions: 2,
  },
  {
    jobRoleName: "Principal Product Manager",
    description: "Define product vision across multiple product lines.",
    responsibilities: "Strategic planning, portfolio management, team leadership",
    jobSpecLink: "https://company.com/careers/principal-product-manager",
    location: "London, UK",
    capability: "Product",
    band: "Principal",
    closingDate: "2026-01-20",
    status: "open",
    numberOfOpenPositions: 1,
  },
  {
    jobRoleName: "Product Manager - Data Platform",
    description: "Manage data platform products and tools.",
    responsibilities: "Product strategy, roadmap planning, feature prioritization",
    jobSpecLink: "https://company.com/careers/pm-data-platform",
    location: "Remote, UK",
    capability: "Product",
    band: "Mid",
    closingDate: "2025-11-15",
    status: "open",
    numberOfOpenPositions: 1,
  },

  // DESIGN (5 roles)
  {
    jobRoleName: "Junior UX Designer",
    description: "Begin your design career creating user experiences.",
    responsibilities: "UI design, wireframing, prototyping, user research",
    jobSpecLink: "https://company.com/careers/junior-ux-designer",
    location: "London, UK",
    capability: "Design",
    band: "Junior",
    closingDate: "2025-12-15",
    status: "open",
    numberOfOpenPositions: 2,
  },
  {
    jobRoleName: "UX Designer",
    description: "Create intuitive user experiences for digital products.",
    responsibilities: "User research, wireframing, usability testing, design systems",
    jobSpecLink: "https://company.com/careers/ux-designer",
    location: "Bristol, UK",
    capability: "Design",
    band: "Mid",
    closingDate: "2025-11-20",
    status: "open",
    numberOfOpenPositions: 3,
  },
  {
    jobRoleName: "Senior UX Designer",
    description: "Lead design initiatives and mentor designers.",
    responsibilities: "Design leadership, user research, design strategy, mentoring",
    jobSpecLink: "https://company.com/careers/senior-ux-designer",
    location: "Manchester, UK",
    capability: "Design",
    band: "Senior",
    closingDate: "2025-12-01",
    status: "open",
    numberOfOpenPositions: 2,
  },
  {
    jobRoleName: "Principal Design Lead",
    description: "Define design vision and strategy.",
    responsibilities: "Design strategy, team leadership, design system governance",
    jobSpecLink: "https://company.com/careers/principal-design-lead",
    location: "London, UK",
    capability: "Design",
    band: "Principal",
    closingDate: "2026-01-10",
    status: "open",
    numberOfOpenPositions: 1,
  },
  {
    jobRoleName: "Product Designer",
    description: "Own end-to-end design for product features.",
    responsibilities: "Product design, prototyping, visual design, design QA",
    jobSpecLink: "https://company.com/careers/product-designer",
    location: "Remote, UK",
    capability: "Design",
    band: "Mid",
    closingDate: "2025-11-25",
    status: "open",
    numberOfOpenPositions: 2,
  },

  // PLATFORM (5 roles)
  {
    jobRoleName: "Junior Platform Engineer",
    description: "Learn platform infrastructure and tooling.",
    responsibilities: "Infrastructure support, tool maintenance, monitoring",
    jobSpecLink: "https://company.com/careers/junior-platform-engineer",
    location: "London, UK",
    capability: "Platform",
    band: "Junior",
    closingDate: "2025-12-20",
    status: "open",
    numberOfOpenPositions: 3,
  },
  {
    jobRoleName: "Platform Engineer",
    description: "Build platform infrastructure and CI/CD pipelines.",
    responsibilities: "Infrastructure management, CI/CD, automation, monitoring",
    jobSpecLink: "https://company.com/careers/platform-engineer",
    location: "Manchester, UK",
    capability: "Platform",
    band: "Mid",
    closingDate: "2025-11-22",
    status: "open",
    numberOfOpenPositions: 4,
  },
  {
    jobRoleName: "Senior Platform Engineer",
    description: "Lead platform initiatives and architect solutions.",
    responsibilities: "Platform architecture, team leadership, infrastructure as code",
    jobSpecLink: "https://company.com/careers/senior-platform-engineer",
    location: "Birmingham, UK",
    capability: "Platform",
    band: "Senior",
    closingDate: "2025-11-28",
    status: "open",
    numberOfOpenPositions: 2,
  },
  {
    jobRoleName: "Principal Platform Architect",
    description: "Define platform strategy and architecture.",
    responsibilities: "Strategic planning, architecture governance, innovation",
    jobSpecLink: "https://company.com/careers/principal-platform-architect",
    location: "London, UK",
    capability: "Platform",
    band: "Principal",
    closingDate: "2026-01-25",
    status: "open",
    numberOfOpenPositions: 1,
  },
  {
    jobRoleName: "DevOps Engineer",
    description: "Maintain infrastructure and deployment processes.",
    responsibilities: "Infrastructure management, automation, security, CI/CD",
    jobSpecLink: "https://company.com/careers/devops-engineer",
    location: "Edinburgh, UK",
    capability: "Platform",
    band: "Senior",
    closingDate: "2025-10-25",
    status: "open",
    numberOfOpenPositions: 1,
  },

  // QUALITY (5 roles)
  {
    jobRoleName: "Junior QA Engineer",
    description: "Learn testing methodologies and automation.",
    responsibilities: "Manual testing, test cases, bug reporting, automation learning",
    jobSpecLink: "https://company.com/careers/junior-qa-engineer",
    location: "London, UK",
    capability: "Quality",
    band: "Junior",
    closingDate: "2025-12-10",
    status: "open",
    numberOfOpenPositions: 3,
  },
  {
    jobRoleName: "QA Engineer",
    description: "Ensure software quality through testing.",
    responsibilities: "Test planning, automated testing, bug reporting, CI/CD",
    jobSpecLink: "https://company.com/careers/qa-engineer",
    location: "Leeds, UK",
    capability: "Quality",
    band: "Mid",
    closingDate: "2025-11-05",
    status: "open",
    numberOfOpenPositions: 4,
  },
  {
    jobRoleName: "Senior QA Engineer",
    description: "Lead quality initiatives and mentor QA team.",
    responsibilities: "Testing strategy, automation frameworks, team leadership",
    jobSpecLink: "https://company.com/careers/senior-qa-engineer",
    location: "Manchester, UK",
    capability: "Quality",
    band: "Senior",
    closingDate: "2025-11-15",
    status: "open",
    numberOfOpenPositions: 2,
  },
  {
    jobRoleName: "QA Engineer (Test Automation)",
    description: "Focus on test automation & CI/CD integration.",
    responsibilities: "Automated testing, test frameworks, CI/CD, API testing",
    jobSpecLink: "https://company.com/careers/qa-automation-engineer",
    location: "Cardiff, UK",
    capability: "Quality",
    band: "Mid",
    closingDate: "2025-11-30",
    status: "open",
    numberOfOpenPositions: 2,
  },
  {
    jobRoleName: "Principal QA Architect",
    description: "Define quality strategy and standards.",
    responsibilities: "Quality strategy, test architecture, process definition",
    jobSpecLink: "https://company.com/careers/principal-qa-architect",
    location: "London, UK",
    capability: "Quality",
    band: "Principal",
    closingDate: "2026-01-15",
    status: "open",
    numberOfOpenPositions: 1,
  },

  // ARCHITECTURE (5 roles)
  {
    jobRoleName: "Solutions Architect",
    description: "Design enterprise technical solutions.",
    responsibilities: "Architecture design, technical documentation, consultation",
    jobSpecLink: "https://company.com/careers/solutions-architect",
    location: "London, UK",
    capability: "Architecture",
    band: "Senior",
    closingDate: "2025-12-15",
    status: "open",
    numberOfOpenPositions: 2,
  },
  {
    jobRoleName: "Cloud Architect",
    description: "Design cloud solutions on AWS, Azure, and GCP.",
    responsibilities: "Cloud architecture, migration planning, cost optimization",
    jobSpecLink: "https://company.com/careers/cloud-architect",
    location: "London, UK (Hybrid - 2 days office)",
    capability: "Architecture",
    band: "Principal",
    closingDate: "2025-12-20",
    status: "open",
    numberOfOpenPositions: 1,
  },
  {
    jobRoleName: "Enterprise Architect",
    description: "Define enterprise architecture standards.",
    responsibilities: "Enterprise architecture, strategy alignment, governance",
    jobSpecLink: "https://company.com/careers/enterprise-architect",
    location: "Manchester, UK",
    capability: "Architecture",
    band: "Principal",
    closingDate: "2025-11-25",
    status: "open",
    numberOfOpenPositions: 1,
  },
  {
    jobRoleName: "Security Architect",
    description: "Design security architectures and standards.",
    responsibilities: "Security architecture, threat modeling, compliance",
    jobSpecLink: "https://company.com/careers/security-architect",
    location: "Birmingham, UK",
    capability: "Architecture",
    band: "Senior",
    closingDate: "2025-12-05",
    status: "open",
    numberOfOpenPositions: 1,
  },
  {
    jobRoleName: "Integration Architect",
    description: "Design integration patterns and system integration.",
    responsibilities: "Integration architecture, API design, technical guidance",
    jobSpecLink: "https://company.com/careers/integration-architect",
    location: "Remote, UK",
    capability: "Architecture",
    band: "Senior",
    closingDate: "2025-11-18",
    status: "open",
    numberOfOpenPositions: 2,
  },

  // BUSINESS ANALYSIS (5 roles)
  {
    jobRoleName: "Junior Business Analyst",
    description: "Learn to bridge business and technical requirements.",
    responsibilities: "Requirements gathering, documentation, process mapping",
    jobSpecLink: "https://company.com/careers/junior-business-analyst",
    location: "London, UK",
    capability: "Business Analysis",
    band: "Junior",
    closingDate: "2025-12-01",
    status: "open",
    numberOfOpenPositions: 3,
  },
  {
    jobRoleName: "Business Analyst",
    description: "Bridge business requirements with technical solutions.",
    responsibilities: "Requirements gathering, process analysis, documentation",
    jobSpecLink: "https://company.com/careers/business-analyst",
    location: "Cardiff, UK",
    capability: "Business Analysis",
    band: "Mid",
    closingDate: "2025-10-28",
    status: "closed",
    numberOfOpenPositions: 0,
  },
  {
    jobRoleName: "Senior Business Analyst",
    description: "Lead business analysis and manage complex requirements.",
    responsibilities: "Requirements leadership, process improvement, mentoring",
    jobSpecLink: "https://company.com/careers/senior-business-analyst",
    location: "Manchester, UK",
    capability: "Business Analysis",
    band: "Senior",
    closingDate: "2025-11-20",
    status: "open",
    numberOfOpenPositions: 2,
  },
  {
    jobRoleName: "Principal Business Analyst",
    description: "Define business analysis strategy.",
    responsibilities: "Strategic analysis, transformation leadership, team leadership",
    jobSpecLink: "https://company.com/careers/principal-business-analyst",
    location: "London, UK",
    capability: "Business Analysis",
    band: "Principal",
    closingDate: "2026-01-05",
    status: "open",
    numberOfOpenPositions: 1,
  },
  {
    jobRoleName: "Business Systems Analyst",
    description: "Analyze and optimize business systems.",
    responsibilities: "Systems analysis, process optimization, requirements management",
    jobSpecLink: "https://company.com/careers/business-systems-analyst",
    location: "Bristol, UK",
    capability: "Business Analysis",
    band: "Mid",
    closingDate: "2025-11-12",
    status: "open",
    numberOfOpenPositions: 2,
  },

  // SECURITY (5 roles)
  {
    jobRoleName: "Junior Security Analyst",
    description: "Start your cybersecurity career.",
    responsibilities: "Security monitoring, incident response support, log analysis",
    jobSpecLink: "https://company.com/careers/junior-security-analyst",
    location: "London, UK",
    capability: "Security",
    band: "Junior",
    closingDate: "2025-12-18",
    status: "open",
    numberOfOpenPositions: 2,
  },
  {
    jobRoleName: "Security Engineer",
    description: "Implement and maintain security controls.",
    responsibilities: "Security monitoring, vulnerability management, incident response",
    jobSpecLink: "https://company.com/careers/security-engineer",
    location: "Manchester, UK",
    capability: "Security",
    band: "Mid",
    closingDate: "2025-11-22",
    status: "open",
    numberOfOpenPositions: 3,
  },
  {
    jobRoleName: "Senior Security Engineer",
    description: "Lead security initiatives and protect assets.",
    responsibilities: "Security strategy, threat analysis, incident response leadership",
    jobSpecLink: "https://company.com/careers/senior-security-engineer",
    location: "Glasgow, UK",
    capability: "Security",
    band: "Senior",
    closingDate: "2025-11-30",
    status: "open",
    numberOfOpenPositions: 2,
  },
  {
    jobRoleName: "Cybersecurity Specialist",
    description: "Protect assets through security monitoring.",
    responsibilities: "Security monitoring, vulnerability assessment, threat intelligence",
    jobSpecLink: "https://company.com/careers/cybersecurity-specialist",
    location: "Edinburgh, UK",
    capability: "Security",
    band: "Senior",
    closingDate: "2025-12-08",
    status: "open",
    numberOfOpenPositions: 2,
  },
  {
    jobRoleName: "Principal Security Officer",
    description: "Define security strategy organization-wide.",
    responsibilities: "Security strategy, governance, compliance, risk management",
    jobSpecLink: "https://company.com/careers/principal-security-officer",
    location: "London, UK",
    capability: "Security",
    band: "Principal",
    closingDate: "2026-01-30",
    status: "open",
    numberOfOpenPositions: 1,
  },

  // EDGE CASES (9 roles)
  {
    jobRoleName: "Urgent: Infrastructure Engineer",
    description: "Immediate need for infrastructure engineer.",
    responsibilities: "Infrastructure management, capacity planning, security",
    jobSpecLink: "https://company.com/careers/urgent-infrastructure",
    location: "London, UK",
    capability: "Platform",
    band: "Senior",
    closingDate: "2025-10-10",
    status: "open",
    numberOfOpenPositions: 1,
  },
  {
    jobRoleName: "Graduate Software Engineer (2026 Intake)",
    description: "Join our 2026 graduate program.",
    responsibilities: "Learning, project work, mentorship, professional development",
    jobSpecLink: "https://company.com/careers/graduate-2026",
    location: "Multiple UK Locations",
    capability: "Engineering",
    band: "Junior",
    closingDate: "2026-03-31",
    status: "open",
    numberOfOpenPositions: 10,
  },
  {
    jobRoleName: "Data Intern",
    description: "Summer internship in data analytics.",
    responsibilities: "Data analysis, reporting, learning",
    jobSpecLink: "https://company.com/careers/data-intern",
    location: "London",
    capability: "Data & Analytics",
    band: "Junior",
    closingDate: "2025-11-01",
    status: "open",
    numberOfOpenPositions: 5,
  },
  {
    jobRoleName: "Software Engineering Apprentice",
    description: "Level 4 apprenticeship with training.",
    responsibilities: "Learning fundamentals, projects, training, certification",
    jobSpecLink: "https://company.com/careers/apprentice",
    location: "Manchester, UK",
    capability: "Engineering",
    band: "Junior",
    closingDate: "2025-10-31",
    status: "open",
    numberOfOpenPositions: 8,
  },
  {
    jobRoleName: "IT Support Specialist",
    description: "Provide technical support for enterprise applications.",
    responsibilities: "User support, issue triage, documentation, training",
    jobSpecLink: "https://company.com/careers/it-support",
    location: "Multiple Locations",
    capability: "Platform",
    band: "Junior",
    closingDate: "2025-12-31",
    status: "open",
    numberOfOpenPositions: 15,
  },
  {
    jobRoleName: "Technical Writer",
    description: "Create technical documentation for engineering.",
    responsibilities: "Documentation writing, API docs, user guides, tutorials",
    jobSpecLink: "https://company.com/careers/technical-writer",
    location: "Remote, UK/EU",
    capability: "Engineering",
    band: "Mid",
    closingDate: "2025-11-18",
    status: "open",
    numberOfOpenPositions: 2,
  },
  {
    jobRoleName: "Workday Analyst (Part-Time)",
    description: "Part-time Workday administration and reporting.",
    responsibilities: "Report creation, system admin, user support, documentation",
    jobSpecLink: "https://company.com/careers/workday-analyst-pt",
    location: "Flexible, UK",
    capability: "Workday",
    band: "Junior",
    closingDate: "2025-12-15",
    status: "open",
    numberOfOpenPositions: 1,
  },
  {
    jobRoleName: "Internship Program 2026",
    description: "Summer 2026 internship across all teams.",
    responsibilities: "Project work, collaboration, learning, presentations",
    jobSpecLink: "https://company.com/careers/internship-2026",
    location: "Various UK Locations",
    capability: "Engineering",
    band: "Junior",
    closingDate: "2026-02-28",
    status: "open",
    numberOfOpenPositions: 20,
  },
];
