name: Update Expired Job Roles

on:
  # Run every night at 3 AM UTC
  schedule:
    - cron: '0 3 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  update-expired-jobs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Call API to update expired job roles
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL || 'https://your-api-domain.com' }}
        run: |
          echo "Calling update expired jobs API..."
          
          RESPONSE=$(curl -s -w "%{http_code}" -X PUT "$API_BASE_URL/api/jobs/update-expired")
          HTTP_CODE=$(echo "$RESPONSE" | tail -c 4)
          BODY=$(echo "$RESPONSE" | head -c -4)
          
          echo "HTTP Status: $HTTP_CODE"
          echo "Response: $BODY"
          
          # Check if the request was successful
          if [ "$HTTP_CODE" -eq 200 ]; then
            echo "✅ Successfully updated expired job roles"
            
            # Parse the response to show how many jobs were updated
            UPDATED_COUNT=$(echo "$BODY" | grep -o '"updatedCount":[0-9]*' | grep -o '[0-9]*' || echo "unknown")
            echo "📊 Updated $UPDATED_COUNT job role(s) to closed status"
          else
            echo "❌ Failed to update expired job roles (HTTP $HTTP_CODE)"
            echo "Response body: $BODY"
            exit 1
          fi

      - name: Create issue on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Job Role Update Failed - ' + new Date().toISOString().split('T')[0],
              body: '❌ The scheduled job role update failed.\n\n' +
                    '**When:** ' + new Date().toISOString() + '\n' +
                    '**Workflow:** update-expired-jobs\n' +
                    '**Action needed:** Check the API endpoint and database connection.\n\n' +
                    '[View workflow run](' + context.payload.repository.html_url + '/actions/runs/' + context.runId + ')',
              labels: ['bug', 'automated-workflow']
            })